services:
  frontend:
    image: maeddes/hse25frontend:flask
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      API_SERVER_URL: "http://api:3000"
    networks:
      - shoppingnet

  api:
    # Build the API from the local directory
    build: backend/ShoppingApi

    # Or use a pre-built image from GitHub Container Registry
    # image: ghcr.io/professornova/distributed-systems:latest

    container_name: shopping_api
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "http://+:3000"
      POSTGRES_CONNECTION: "Host=db;Port=5432;Database=shopping_db;Username=shopping_user;Password=shopping_pass"
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "3000:3000"
    networks:
      - shoppingnet

  db:
    image: postgres:15
    container_name: shopping_db
    environment:
      POSTGRES_USER: shopping_user
      POSTGRES_PASSWORD: shopping_pass
      POSTGRES_DB: shopping_db
    networks:
      - shoppingnet

networks:
  shoppingnet:
    driver: bridge
