services:
  frontend:
    image: maeddes/hse25frontend:flask
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      API_SERVER_URL: http://backend:3000
    networks:
      - app-network

  backend:
    build:
      context: ./backend/DotNetApi
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - ASPNETCORE_URLS=http://+:3000
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
