on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Image and Push
        run: |
          docker build -t ghcr.io/professornova/distributed-systems:latest ./backend/ShoppingApi/Dockerfile
          docker run --rm ghcr.io/professornova/distributed-systems:latest
          docker push ghcr.io/professornova/distributed-systems:latest
