on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, run and push Docker image
        env:
          # Lowercase the owner/repo string
          IMAGE_TAG: ghcr.io/${GITHUB_REPOSITORY,,}:latest
        run: |
          # Build needs a directory context; -f points at the Dockerfile
          docker build --tag $IMAGE_TAG \
            -f ./backend/ShoppingApi/Dockerfile \
            ./backend/ShoppingApi
          docker run --rm $IMAGE_TAG
          docker push $IMAGE_TAG
